### ISSUE TITLE
[OAI] If resumption token given, it should be the only argument other than the "verb" argument

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#1]
"Then an attempt was made to retrieve the next set with the resumption token provided, i.e. http://search.records.nsw.gov.au/oai?verb=ListRecords&resumptionToken=rif::::2, but we get an error."  

"I’ve just checked the OAI PMH spec and this is an error in our implementation. Your query is correct, however we seem to be requiring a metadataPrefix here which is wrong on our part (acc. to the spec, if you have a resumptionToken it should be the only argument besides the ListRecords verb). This should be easy for us to fix (I will advise when it is). In the meantime, you can get things going again if you like by using this url: http://search.records.nsw.gov.au/oai?verb=ListRecords&metadataPrefix=rif&resumptionToken=rif::::2"

**Comment by wisanup** [comment]
This is fixed at the current production. Please verify.

**Comment by richardlehane** [comment]
Thanks now works without metadataPrefix. Can you return a "badArgument" error now when someone attempts to include any additional arguments with the resumptionToken (besides the verb argument of course).
This prevents nonsense requests like:
http://search.records.nsw.gov.au/oai?verb=ListRecords&metadataPrefix=mod&resumptionToken=rif::::2 (where I attempt to get both RIF and MODS)
Note: should return "badArgument" even if they are consistent in the metadataPrefix and resumptionToken

**Comment by wisanup** [comment]
please open the new issue for that request

**Comment by richardlehane** [comment]
Raising new issue!
