### ISSUE TITLE
Some items returning corrupted response!!

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#10]
e.g. http://search.records.nsw.gov.au/items/151972

For more examples, try these items: http://search.records.nsw.gov.au/series/12949/items

![image002](https://f.cloud.github.com/assets/157422/412695/ccd6c360-abc6-11e2-95e2-edb523bc20c6.jpg)

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
Looks good, thanks for fix
