### ISSUE TITLE
Content spilling out of page

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#12]
(Reported by Anthea): I was getting some links from Search for a webpage and noticed that the content is spilling out of the page – not sure if this happens for every page
http://search.records.nsw.gov.au/agencies/1767

The page works in Firefox 20 but can reproduce the bug in Chrome.

**Comment by wisanup** [comment]
This is fixed at css by forcing the long URL to be wrapped.

**Comment by richardlehane** [comment]
Works in firefox still but in Chrome get a new bug. Word wrapping breaks on description text column:
![image002](https://f.cloud.github.com/assets/157422/481555/0cf43782-b867-11e2-8c49-e8cb3d66be2a.jpg)

**Comment by wisanup** [comment]
Have a look again. I've added a little tweak so this will effect only to html link.

**Comment by richardlehane** [comment]
Hmmm that just restored the old bug on Chrome again (wrapping works but breaking out of div) :-1:

**Comment by richardlehane** [comment]
:+1: :100: :8ball:

**Comment by richardlehane** [comment]
sorry forgot you were going to try a special fix on the hrefs

**Comment by richardlehane** [comment]
:+1: :100:
