### ISSUE TITLE
Series RIF-CS views: collection element

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#13]
For all the Series RIF-CS views, on the collection element:
1) change the type attribute from "repository" to "collection"
2) add a dateModified attribute giving the series' last amendment date in the format YYYY-MM-DD

**Comment by wisanup** [comment]
Where should the dateModified attribute belongs? Should I add it under [collection] node or somewhere else?

**Comment by richardlehane** [comment]
add it to the collection element please (next to the type attribute)

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
Checked, thanks
