### ISSUE TITLE
Series RIF-CS views: new dates element

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#14]
Please add a new element immediately below the identifier element. The value should be the series contents start and end dates.
 &lt;dates type="dc.created"&gt;
        &lt;date type="dateFrom" dateFormat="W3CDTF"&gt;YYYY or YYYY-MM or YYYY-MM-DD&lt;/date&gt;
       &lt;date type="dateTo" dateFormat="W3CDTF"&gt;YYYY or YYYY-MM or YYYY-MM-DD&lt;/date&gt;
&lt;/dates&gt;

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
Checked, thanks
