### ISSUE TITLE
Series RIF-CS views: new location element

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#15]
Please add a new location element immediately beneath the name element.

&lt;location&gt;
        &lt;address&gt;
          &lt;electronic type="url"&gt;
           &lt;value&gt;ENTITY URL&lt;/value&gt;
          &lt;/electronic&gt;
          &lt;physical type="streetAddress"&gt;
            &lt;addressPart type="text"&gt;REPOSITORY STREET ADDRESS&lt;/addressPart&gt;
         &lt;/physical&gt;
        &lt;/address&gt;
    &lt;/location&gt;

Entity URL should be e.g. http://search.records.nsw.gov.au/series/1

Repository Street Address should be derived from the repository field and should be one of the following values:

Western Sydney Records Centre
143 O'Connell Street KINGSWOOD NSW

University of New England Heritage Centre
C. B. Newling Campus
Cnr Dangar and Kentucky Sts ARMIDALE NSW

Outback Archives Broken Hill City Library
Blende Street BROKEN HILL NSW

Newcastle Region Library
Laman Street NEWCASTLE NSW

Archives Rare Books and Special Collections (University of Newcastle)
Level 2 Auchmuty Library
University of Newcastle
University Drive CALLAGHAN NSW

Charles Sturt University Regional Archives
Blakemore Building Hely Avenue WAGGA WAGGA NSW

The Library, University of Wollongong
Northfields Avenue WOLLONGONG NSW

**Comment by wisanup** [comment]
Is the line break essential for all multi-line addresses?

**Comment by richardlehane** [comment]
Line breaks are preferable - are they a major headache to insert?

**Comment by wisanup** [comment]
I just wanted to confirm. It's OK to add it.

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
In the street address, please include the name of the repository in the first line. So: 
"Western Sydney Records Centre
143 O'Connell Street KINGSWOOD NSW"
rather than: "143 O'Connell Street KINGSWOOD NSW"

**Comment by wisanup** [comment]
It should be OK now.

**Comment by richardlehane** [comment]
Great, thanks
