### ISSUE TITLE
Series RIF-CS views: remove relatedObject with isLocatedIn attribute

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#16]
Please remove the relatedObject element that has a relation type of "isLocatedIn.

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
Works for OAI and list (series.rif) views but not for individual series. E.g. http://search.records.nsw.gov.au/series/1.rif. Empty description elements.

**Comment by wisanup** [comment]
It's hasCreator not isLocatedIn so it's still there. Do you want me to remove every relatedObject?
Empty description should be fixed anyway.

**Comment by richardlehane** [comment]
No, everything is correct in OAI and the list views. It is just that in the individual series view the description element is empty. Otherwise all perfect!

**Comment by wisanup** [comment]
It should be OK now.

**Comment by richardlehane** [comment]
Thanks!
