### ISSUE TITLE
Series RIF-CS views: fix related Info element

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#19]
We have a related info elment that isn't working. It currently gives a blank element for identifier. This element should contain the URL. E.g.:

&lt;relatedInfo&gt;&lt;identifier type="website"&gt;http://search.records.nsw.gov.au/series/ID &lt;/relatedInfo&gt;

**Comment by wisanup** [comment]
This is fixed and deployed to the production. Please verify.

**Comment by richardlehane** [comment]
Thanks
