### ISSUE TITLE
Series RIF-CS views: rights element

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#20]
For all three RIF views please add a new sub-element within the rights element. It should be the first sub-element (so come immediately before the rightsStatement element.

Text should be the same for every series:

&lt;accessRights rightsUri="http://www.records.nsw.gov.au/state-archives/register-of-access-directions" &gt;The State Records Act 1998 (NSW)  provides a general entitlement of public access to State records that are at least 30 years old. For a record to be available under the Act it must be subject to  an 'open to public access' direction.  Some records containing  sensitive information may be closed for longer than 30 years under a ‘closed to public access’ direction. View access directions at : http://www.records.nsw.gov.au/state-archives/register-of-access-directions &lt;/accessRights&gt;

**Comment by richardlehane** [comment]
I had to add two spaces to get the angle brackets to  work (both after the hrefs): please delete those two spaces when you implement

**Comment by wisanup** [comment]
I've applied the change to the production. Please verify

**Comment by richardlehane** [comment]
Thanks Nott that looks great. Sorry could you fix one error that came from me (not yours): in the phrase "access directions at :" could you please trim the whitespace before the colon :+1: thanks!

**Comment by wisanup** [comment]
all done. please verify.

**Comment by richardlehane** [comment]
Checked thanks!
