### ISSUE TITLE
In RIF views for agencies and people

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#33]
Where there is no end date, omit the entire node.

For example, an error is caused by:

&lt;existenceDates&gt;
  &lt;startDate dateFormat="W3CDTF"&gt;1869-09-29T00:00:00+1000&lt;/startDate&gt;
  &lt;endDate dateFormat="W3CDTF"/&gt;
&lt;/existenceDates&gt;

, but not by:

&lt;existenceDates&gt;
  &lt;startDate dateFormat="W3CDTF"&gt;1869-09-29T00:00:00+1000&lt;/startDate&gt;
&lt;/existenceDates&gt;

**Comment by wisanup** [comment]
Fixed 3d80fe86bcd786252116cd7f1f4f5699ffdf29a9
