### ISSUE TITLE
RIF templates

### ISSUE THREAD

**Issue by richardlehane** [srnsw/State-Records-Search#4]
1. Please remove &lt;license&gt; elements from &lt;rights&gt; element.
2. The OAI RIF template works for "hasCreator" when it is a person, not agency. However the plain RIF template http://search.records.nsw.gov.au/series.rif returns an empty element. [Would really be preferable in we could be using the same templates for OAI and regular API routes to avoid these errors]

**Comment by wisanup** [comment]
Do we take [license] element off instead of to change wording from license to licence?

**Comment by richardlehane** [comment]
Yes, please just remove entirely

**Comment by wisanup** [comment]
For the 2), do you mean as following?
- For agencies use hasCollector
- For person use hasCreator

**Comment by richardlehane** [comment]
No in both cases should be "hasCreator". This issue doesn't relate to the RIF template used by OAI controller. It is only a problem is only for the plain RIF template i.e. http://search.records.nsw.gov.au/series.rif. If you click on that you'll see that person creators return blank elements.

**Comment by wisanup** [comment]
This is fixed at the current production. Please verify.

**Comment by richardlehane** [comment]
Moar broken: now I get Internal Server error for http://search.records.nsw.gov.au/series.rif

**Comment by richardlehane** [comment]
Raised new issue, closing this one
